# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: f1.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'f1.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66\x31.proto\x12\x02\x66\x31\"\x90\x01\n\rTelemetryData\x12\x11\n\tdriver_id\x18\x01 \x01(\t\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x03\x12\r\n\x05speed\x18\x03 \x01(\x02\x12\x0b\n\x03rpm\x18\x04 \x01(\x02\x12\x0c\n\x04gear\x18\x05 \x01(\x05\x12\x10\n\x08throttle\x18\x06 \x01(\x02\x12\r\n\x05\x62rake\x18\x07 \x01(\x02\x12\x0b\n\x03\x64rs\x18\x08 \x01(\x02\"8\n\x0fTransferSummary\x12\x15\n\rtotal_packets\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t2Q\n\x12\x46\x31TelemetryService\x12;\n\x0fStreamTelemetry\x12\x11.f1.TelemetryData\x1a\x13.f1.TransferSummary(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'f1_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYDATA']._serialized_start=17
  _globals['_TELEMETRYDATA']._serialized_end=161
  _globals['_TRANSFERSUMMARY']._serialized_start=163
  _globals['_TRANSFERSUMMARY']._serialized_end=219
  _globals['_F1TELEMETRYSERVICE']._serialized_start=221
  _globals['_F1TELEMETRYSERVICE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
