# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import f1_pb2 as f1__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in f1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class F1TelemetryServiceStub(object):
    """1. 서비스 정의: Rust 서버가 제공할 기능
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTelemetry = channel.stream_unary(
                '/f1.F1TelemetryService/StreamTelemetry',
                request_serializer=f1__pb2.TelemetryData.SerializeToString,
                response_deserializer=f1__pb2.TransferSummary.FromString,
                _registered_method=True)


class F1TelemetryServiceServicer(object):
    """1. 서비스 정의: Rust 서버가 제공할 기능
    """

    def StreamTelemetry(self, request_iterator, context):
        """스트림 방식으로 데이터를 계속 보냄 (Client Streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_F1TelemetryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTelemetry': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=f1__pb2.TelemetryData.FromString,
                    response_serializer=f1__pb2.TransferSummary.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'f1.F1TelemetryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('f1.F1TelemetryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class F1TelemetryService(object):
    """1. 서비스 정의: Rust 서버가 제공할 기능
    """

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/f1.F1TelemetryService/StreamTelemetry',
            f1__pb2.TelemetryData.SerializeToString,
            f1__pb2.TransferSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
